{% set version = "2.42.4" %}
{% set version_major = version.split('.', 1)[0] %}
{% set version_majmin = version.rsplit('.', 1)[0] %}
{% set sha256 = "225280a2a69ee4cce6452a1a92d9297cc1b34a8faface2bf2b4b9da48f044de3" %}

package:
  name: librsvg
  version: {{ version }}

source:
  fn: librsvg-{{ version }}.tar.xz
  url: http://ftp.gnome.org/pub/gnome/sources/librsvg/{{ version_majmin }}/librsvg-{{ version }}.tar.xz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - toolchain
    - pkg-config
    - glib 2.55.*
    - libxml2 2.9.*
    - cairo 1.14.*
    - gdk-pixbuf 2.36.*
    - libcroco 0.6.*
    - pango 1.40.*
  run:
    - glib 2.55.*
    - libxml2 2.9.*
    - cairo 1.14.*
    - gdk-pixbuf 2.36.*
    - libcroco 0.6.*
    - pango 1.40.*

test:
  commands:
    - test -f $PREFIX/lib/librsvg-{{ version_major }}$SHLIB_EXT
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]
    - rsvg-convert --version

about:
  home: https://wiki.gnome.org/Projects/LibRsvg
  license: GPLv2
  license_file: COPYING
  summary: librsvg is a library to render SVG files using cairo.

extra:
  recipe-maintainers:
    - jenzopr
    - pkgw
