{% set version = "2.47.3" %}
{% set version_major = version.split('.', 1)[0] %}
{% set version_majmin = version.rsplit('.', 1)[0] %}
{% set sha256 = "bf8b970f5e72edb66be79e11df2b20f180abff5029c90e94d6c254476b0ba5fa" %}

package:
  name: librsvg
  version: {{ version }}

source:
  fn: librsvg-{{ version }}.tar.xz
  url: http://ftp.gnome.org/pub/gnome/sources/librsvg/{{ version_majmin }}/librsvg-{{ version }}.tar.xz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]
  run_exports:
    # Looks good but no new info after 2.43 so keeping it x.x for safety.
    # https://abi-laboratory.pro/?view=timeline&l=librsvg
    - {{ pin_subpackage('librsvg', max_pin='x') }}

requirements:
  build:
    - make
    - pkg-config
    - rust
    - {{ compiler('c') }}
  host:
    - glib
    - libxml2
    - cairo
    - gdk-pixbuf
    - libcroco 0.6.*
    - pango
  run:
    - glib
    - libxml2
    - cairo
    - gdk-pixbuf
    - libcroco 0.6.*
    - pango

test:
  commands:
    - test -f $PREFIX/lib/librsvg-{{ version_major }}$SHLIB_EXT
    - rsvg-convert --version

about:
  home: https://wiki.gnome.org/Projects/LibRsvg
  license: LGPLv2
  license_file: COPYING.LIB
  summary: librsvg is a library to render SVG files using cairo.

extra:
  recipe-maintainers:
    - jenzopr
    - pkgw
