{% set version = "2.45.7" %}
{% set version_major = version.split('.', 1)[0] %}
{% set version_majmin = version.rsplit('.', 1)[0] %}
{% set sha256 = "d4399eb76eb4e955fd36a5e536e4cb965ccfafbbc72e3b43495e08ac2a61f993" %}

package:
  name: librsvg
  version: {{ version }}

source:
  fn: librsvg-{{ version }}.tar.xz
  url: http://ftp.gnome.org/pub/gnome/sources/librsvg/{{ version_majmin }}/librsvg-{{ version }}.tar.xz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - pkg-config
    - rust
    - {{ compiler('c') }}
  host:
    - glib
    - libxml2
    - cairo
    - gdk-pixbuf 2.36.*
    - libcroco 0.6.*
    - pango
  run:
    - glib
    - libxml2
    - cairo
    - gdk-pixbuf 2.36.*
    - libcroco 0.6.*
    - pango

test:
  commands:
    - test -f $PREFIX/lib/librsvg-{{ version_major }}$SHLIB_EXT
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]
    - rsvg-convert --version

about:
  home: https://wiki.gnome.org/Projects/LibRsvg
  license: GPLv2
  license_file: COPYING
  summary: librsvg is a library to render SVG files using cairo.

extra:
  recipe-maintainers:
    - jenzopr
    - pkgw
